// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Phoenix_The_Fall_Web_application.DataBase;

#nullable disable

namespace Phoenix_The_Fall_Web_application.Migrations
{
    [DbContext(typeof(YourDbContext))]
    [Migration("20250514102441_MakePlayerWeaponsIdAutoIncrement")]
    partial class MakePlayerWeaponsIdAutoIncrement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.ClassLoadout", b =>
                {
                    b.Property<int>("PlayerClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("GadgetId")
                        .HasColumnType("integer");

                    b.Property<int?>("MainWeaponId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryWeaponId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerClassId");

                    b.HasIndex("GadgetId");

                    b.HasIndex("MainWeaponId");

                    b.HasIndex("SecondaryWeaponId");

                    b.ToTable("ClassLoadouts");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectorCount")
                        .HasColumnType("integer");

                    b.Property<int>("SizeX")
                        .HasColumnType("integer");

                    b.Property<int>("SizeY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Team1Score")
                        .HasColumnType("real");

                    b.Property<float>("Team2Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.PlayerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerClasses");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.PlayerWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Headshots")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<double>("TimeUsed")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalShots")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WeaponId");

                    b.ToTable("PlayerWeapons");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassRestriction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PrefabPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("WeaponCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WeaponСlassRequirement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.ClassLoadout", b =>
                {
                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Weapon", "Gadget")
                        .WithMany()
                        .HasForeignKey("GadgetId");

                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Weapon", "MainWeapon")
                        .WithMany()
                        .HasForeignKey("MainWeaponId");

                    b.HasOne("Phoenix_The_Fall_Web_application.Models.PlayerClass", null)
                        .WithOne("ClassLoadout")
                        .HasForeignKey("Phoenix_The_Fall_Web_application.Models.ClassLoadout", "PlayerClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Weapon", "SecondaryWeapon")
                        .WithMany()
                        .HasForeignKey("SecondaryWeaponId");

                    b.Navigation("Gadget");

                    b.Navigation("MainWeapon");

                    b.Navigation("SecondaryWeapon");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Match", b =>
                {
                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.PlayerClass", b =>
                {
                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Player", "Player")
                        .WithMany("PlayerClasses")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.PlayerWeapon", b =>
                {
                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Player", "Player")
                        .WithMany("PlayerWeapons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phoenix_The_Fall_Web_application.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.Player", b =>
                {
                    b.Navigation("PlayerClasses");

                    b.Navigation("PlayerWeapons");
                });

            modelBuilder.Entity("Phoenix_The_Fall_Web_application.Models.PlayerClass", b =>
                {
                    b.Navigation("ClassLoadout")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
